version: '3.8'

services:
  integrations:
    build: .
    ports:
      - "8085:8085"
    environment:
      SERVICE_NAME: integrations
      SERVICE_PORT: 8085
      DEBUG: "true"
    volumes:
      - ./src:/app/src
