# Integrations Routes
# Routes for external tool integration APIs (JIRA, Bitbucket, etc.)
# All routes follow R1 service contracts: /v1 base path, required headers

routes:
  - name: integrations-api
    service: integrations
    paths:
      - /v1/integrations
    methods:
      - GET
      - POST
      - PUT
      - DELETE
    strip_path: false
    preserve_host: false
    protocols:
      - http
      - https
    tags:
      - r1
      - integration-route
      - integrations

  - name: integrations-jira
    service: integrations
    paths:
      - /v1/integrations/jira
    methods:
      - GET
      - POST
      - PUT
    strip_path: false
    preserve_host: false
    protocols:
      - http
      - https
    tags:
      - r1
      - integration-route
      - jira

  - name: integrations-bitbucket
    service: integrations
    paths:
      - /v1/integrations/bitbucket
    methods:
      - GET
      - POST
      - PUT
    strip_path: false
    preserve_host: false
    protocols:
      - http
      - https
    tags:
      - r1
      - integration-route
      - bitbucket

  - name: integrations-webhooks
    service: integrations
    paths:
      - /v1/integrations/webhooks
    methods:
      - POST
    strip_path: false
    preserve_host: false
    protocols:
      - http
      - https
    tags:
      - r1
      - integration-route
      - webhooks
